### ISSUE TITLE
can't run tests; can't import qitensor

### ISSUE THREAD

**Issue by silky** [dstahlke/qitensor#1]
the errors i get are

```
04:33 PM noon@master qitensor>./setup.py test                                                             △▲▲ 
running test
Traceback (most recent call last):
  File "./setup.py", line 157, in <module>
    ext_modules = ext_modules,
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "./setup.py", line 56, in run
    import qitensor
ImportError: No module named qitensor

> /home/noon/dev/qitensor/setup.py(56)run()
-> import qitensor
(Pdb) q
⚡ 04:33 PM noon@master qitensor>python                                                                1 ↵ △▲▲ 
Python 2.7.4 (default, Sep 26 2013, 03:20:26) 
[GCC 4.7.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import qitensor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "qitensor/__init__.py", line 39, in <module>
    from qitensor.basefield import *
ImportError: No module named basefield
>>> 
04:33 PM noon@master qitensor>                                                                            △▲▲ 
```

basefield.pyx exists of course. i guess i'm missing something obvious?

**Comment by dstahlke** [comment]
Noon,

It is an unfortunate interaction between doctest, cython, and maybe 
sphinx, and probably due to me not doing it right in setup.py.  
Consequently, you need to install before testing:
./setup install --user
./setup test

If you know how I can fix setup.py in order to make "./setup test" work 
without having to install first, then please let me know!
- Dan

**Comment by silky** [comment]
thanks Dan; that did the trick (I also needed to install cvxopt) but now the tests pass!

**Comment by dstahlke** [comment]
FYI: I now found how to fix this issue.  I had to add the "build/..." path to sys.path; the way to do this was explained by http://stackoverflow.com/a/14369968/1048959  Kind of surprising that this is not automatic...
